### ISSUE TITLE
Install dcm2niix from github release rather than package manager

### ISSUE THREAD

**Issue by fedorov** [MHubAI/mhubio#2]
Per @vkt1414, the version in mhub base image is from 2018!

We should get the latest stable release from https://github.com/rordenlab/dcm2niix/releases instead.

**Comment by LennyN95** [comment]
Thx @fedorov, we'll update and run a test with the latest version. 
I moved the issue to the models repo :)

**Comment by fedorov** [comment]
Ah, ok! I just assumed it belongs to IO, and didn't look around to confirm.
